inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "app/mailers/*"
    - "bin/*"
    - "config/environments/*"
    - "config/*"
    - "db/schema.rb"
    - "spec/*_helper.rb"
    - "vendor/**/*"
    - "config.ru"
    - "Gemfile"
    - "Rakefile"

# Lint
Lint/EmptyBlock:
  Exclude: ["spec/**/*"]
# https://docs.rubocop.org/rubocop/1.17/cops_lint.html#lintemptyblock

Lint/UnusedMethodArgument:
  Exclude: ["app/uploaders/*_uploader.rb"]
# https://docs.rubocop.org/rubocop/1.17/cops_lint.html#lintunusedmethodargument


# Metrics
Metrics/BlockLength:
    Exclude: ["spec/**/*"]
# https://docs.rubocop.org/rubocop/1.17/cops_metrics.html#metricsblocklength


# Style
Style/Documentation:
  Enabled: false
# https://docs.rubocop.org/rubocop/1.17/cops_style.html#styledocumentation

Style/FrozenStringLiteralComment:
  Enabled: false
# https://docs.rubocop.org/rubocop/1.17/cops_style.html#stylefrozenstringliteralcomment

Style/StringLiterals:
  EnforcedStyle: double_quotes
# https://docs.rubocop.org/rubocop/1.17/cops_style.html#stylestringliterals

Style/SymbolArray:
  EnforcedStyle: brackets
# https://docs.rubocop.org/rubocop/1.17/cops_style.html#stylesymbolarray
