source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.3"

gem "rails", "~> 6.1.3", ">= 6.1.3.2"
gem "mysql2", "~> 0.5"
gem "puma", "~> 5.0"
gem "jbuilder", "~> 2.7"
gem "bcrypt", "~> 3.1.7"
gem "image_processing", "~> 1.2"
gem "bootsnap", ">= 1.4.4", require: false
gem "rack-cors"
gem "carrierwave"
gem "mini_magick"
gem "rails-i18n"
gem "faker"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "dotenv-rails"
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
  gem "spring-commands-rspec"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :test do
  gem "rspec_junit_formatter"
end
